### ISSUE TITLE
Flow Tracing v4 with Memgraph

### ISSUE THREAD

**Issue by nc9** [opennem/opennem#435]
With the new `NSW1<->SA1` interconnect coming online on the NEM network in the coming months, the method of flow tracing as implemented in `opennem.core.flows` needs to be updated from using a hard-coded matrix and numpy (which represents the graph). 

The new interconnect also creates a circuitous route between `VIC -> NSW -> SA` which needs to be accounted for.

Proposal is to migrate to a new version of flow tracing based on a graph database - likely [memgraph](https://memgraph.com/).   

### Phase 1: Discovery and Specification

- [x] Spec out potential implementation using memgraph

## Technical Considerations

- Permanent graph database vs in-memory per interval with results aggregated in current database and aggregates
- Validating flows and tests 
- Performance of graph queries
- Note on how historic data is handled with a changing graph - ie. addition of `TAS1` to NEM with basslink, and the period where `NSW1` and `SA1` up to mid-2025 weren't interconnected
- It should still work on historic data when #440 is complete

**Comment by simonhac** [comment]
isn’t this easily solved by having the current graph loaded and using 0MW flows for periods where the interconnector didn’t exist?

**Comment by nc9** [comment]
feature branch has a new memgraph based flow solver:

https://github.com/opennem/opennem/blob/feat-flows-v4-435/opennem/core/flow_solver_graph.py

it accepts as inputs:

```
interconnector_flows:
 - interval: datetime
 - interconnector_code: str
 - network_region_from: str
 - network_region_to: str
 - flow_mw: float (positive or negative, indicating direction)
 - flow_mwh: float (energy for the interval)

regional_generation:
 - interval: datetime
 - network_region: str
 - generation_mwh: float
 - emissions_t: float (total emissions in tonnes CO2)
 - emission_intensity: float (tCO2/MWh)
```

and stores it in the graph database. you can then query out:

```
 regional_flows:
 - network_region: str
 - generation_mwh: float
 - local_emissions_t: float
 - imports_mwh: float
 - import_emissions_t: float
 - exports_mwh: float
 - export_emissions_t: float
 - net_position_mwh: float (positive = net importer)
 - net_emissions_t: float
```

the core flow solver is generic and not tied to OE and is fully unit tested.

to integrate with OE data we have `opennem.aggregates.network_flows_v4.py` which:

- reads the set of interconnectors (supporting new interconnectors as they're added)
- reads the series of generation data for interconnectors from `facility_scada` and shapes the dataframes
- creates `regional_generation` from the `unit_intervals` aggregate and shapes it into a dataframe
- feeds it into the flow solver and takes the output

Here is a test script output comparing the values against v3 of flows:

```
[2025-09-10 07:39:42,120] opennem.core.flow_solver_graph          INFO] Built graph for 2025-09-07 08:00:00: 
{
 'interval': datetime.datetime(2025, 9, 7, 8, 0), 
 'regions_count': 5, 
 'flows_count': 6, 
 'total_generation_mwh': np.float64(1582.4017), 
 'total_emissions_t': np.float64(642.7398)
}

✓ Processed graph: 5 regions, 6 flows
  Total generation: 1582.4 MWh
  Total emissions: 642.7 tCO2

Loading existing at_network_flows data...
✓ Loaded 5 regional records

                                                    Regional Flow Comparison
┏━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━┓
┃        ┃ Generation ┃ Imports v4 ┃ Imports v3 ┃          ┃ Exports v4 ┃ Exports v3 ┃          ┃ Emissions ┃ Emissions ┃      ┃
┃ Region ┃      (MWh) ┃      (MWh) ┃      (MWh) ┃ Δ Import ┃      (MWh) ┃      (MWh) ┃ Δ Export ┃    Imp v4 ┃    Imp v3 ┃ Δ Em ┃
┡━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━┩
│ NSW1   │      454.4 │      113.1 │      113.1 │     -0.0 │        0.0 │        0.0 │      0.0 │     53.44 │     54.46 │ -1.0 │
│ QLD1   │      487.8 │        0.0 │        0.0 │      0.0 │       58.1 │       58.1 │     +0.0 │      0.00 │      0.00 │  0.0 │
│ SA1    │       37.7 │       69.1 │       69.1 │     -0.0 │        0.0 │        0.0 │      0.0 │     28.55 │     28.70 │ -0.1 │
│ TAS1   │      109.3 │        0.0 │        0.0 │      0.0 │        0.0 │        0.0 │      0.0 │      0.00 │      0.00 │  0.0 │
│ VIC1   │      493.3 │        0.0 │        0.0 │      0.0 │      124.1 │      124.1 │      0.0 │      0.00 │      0.00 │  0.0 │
└────────┴────────────┴────────────┴────────────┴──────────┴────────────┴────────────┴──────────┴───────────┴───────────┴──────┘

Summary Statistics:
┌─────────────────────────┬───────┬───────┬──────┐
│ Total Imports (MWh)     │ 182.2 │ 182.2 │ -0.0 │
│ Total Exports (MWh)     │ 182.2 │ 182.2 │ +0.0 │
│ Import Emissions (tCO2) │ 81.99 │ 83.16 │ -1.2 │
│ Export Emissions (tCO2) │ 81.99 │ 83.16 │ -1.2 │
└─────────────────────────┴───────┴───────┴──────┘
```

the emissions are a fraction off

as a test it inserted a dummy `NSW1-SA1` interconnector with circular flows. Here is the output graph:

<img width="3585" height="1475" alt="Image" src="https://github.com/user-attachments/assets/1beecb58-d8d9-4a21-8ec9-164a87ce044e" />

What we have now:

- Setup memgraph with new connection interface, config and connection pool in `opennem.db.memgraph`
- Running memgraph based flow solver and loading both interconnector data into it and regional generation data
- Query the graph for any node state for any interval
- Solves circular flows and accounts for emissions
- Accounts for adding / removing interconnectors at any interval state 

What we need:

- Take the outputs and add them to `market_summary` aggregate clickhouse table adding for each interval for each region `imports` `exports` `import_emissions` and `export_emissions`
- Create materialized view for daily, monthly, yearly aggregates 
- setup the pipeline to ingest into memgraph for each interval, then query out the solution and persist it to `market_summary` in clickhouse (the aggregates auto update)
- update the market API endpoint to include `Metric.IMPORTS` and `Metric.EXPORTS` (MWh) and `Metric.IMPORT_EMISSIONS` and `Metric.EXPORT_EMISSIONS` (tCO2e) 
- Add a flows guide to docs describing all of this 
- Update API docs to include the new metrics with descriptions
- Add example queries in SDK clients showing how to get regional flow balances
- Update TypeScript/Python SDK clients to include the new metric enums
- Add this to recordreactor and records?
